import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "@/stylesheets/style.scss";

import { Header } from "@/components/common/Header";
import { Footer } from "@/components/common/Footer";

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "700"],
  preload: false,
  variable: "--font-noto-sans-jp",
  display: "swap",
  fallback: ["Hiragino Sans", "Hiragino Kaku Gothic ProN", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${notoSansJp.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col px-4">
        <div className="common inner">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
